---
name: "Bulbbot"                 # project name
developers: [                   # developers id stored in array for devOnly & subDevOnly commands
  "190160914765316096",           # mrphilip
  "439396770695479297"            # Kluk
 ]
subDevelopers: [                # sub developers of the bot, giving access to the subDevOnly commands
  "193160566334947340"            # wakfi
]
version: 1.0.0                  # current version
lib: Discord.JS                 # lib used for the bot

# configs
prefix: "!"                     # default prefix
embedColor: "#7289DA"           # default embed color
massCommandSleep: 850       

# client
client:
  tag: "Bulbbot#9083"           # bot full tag
  id: "755149065137815623"      # bot id
  game: "the light shine"       # what the game activity should be
  type: "WATCHING"              # COMPETING (5), WATCHING(3), LISTENING (2), STREAMING (1), PLAYING (0)
  status: "online"              # online, idle, dnd, invisible
  fetchAllUsers: false          # if the bot should fetch all the user on start
  disableMentions: "everyone"   # disable certain mentions

# server
server:                         
  prometheusHost: "localhost"   # host for prometheus
  prometheusPort: 7070          # port for prometheus

# support
supportInvite: "https://discord.gg/cacUmbQ" # support guild invite link

# logs
botDM: "822864336028565534"       # channel id for bot dms 
invite: "822864350603640842"      # channel id for bot invites
error: "822864327303757874"       # channel id for bot errors
debug: "822864498251005952"       # category id for debugging guilds
translation: "820689105854660699" # channel id for untranslated strings
